### ISSUE TITLE
Absence de séparateur entre les 2 dernières collections dans la modale

### ISSUE THREAD

**Issue by floriancargoet** [lairdubois/lairdubois#48]
![image](https://user-images.githubusercontent.com/110431/73355554-af326880-4298-11ea-8cd3-d82b69dc8a96.png)

Bonjour,

Comme on peut le voir sur la capture d'écran, il manque un séparateur entre les 2 dernières collections.

Le border-top de la dernière collection est masqué à cause de cette règle : 
```css
#collections_modal .ladb-collection-row:last-child {
    border: 0;
}
```
